name: Sync Files
on:
  pull_request:
    types:
      - closed

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: latest-ubuntu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Get Last Closed Pull Request Number
        id: get-pr-number
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "PR_NUMBER=$(gh pr list --limit 1 --base main --state closed --json number --jq '.[].number')" >> $GITHUB_OUTPUT

      - name: Create .github/sync.yml
        working-directory: ${{ github.workspace }}/.github
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.get-pr-number.outputs.PR_NUMBER}}
        run: |
          bash ./sync.sh -n $PR_NUMBER

      - name: Get Last Closed Pull Request Info
        id: get-pr-info
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.get-pr-number.outputs.PR_NUMBER}}
        run: |
          PR_TITLE=$(gh pr view $PR_NUMBER --json title --jq '.title')
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_OUTPUT
          PR_BODY=$(gh pr view $PR_NUMBER --json title --jq '.body')
          echo "PR_BODY=$PR_BODY" >> $GITHUB_OUTPUT
          PR_LABELS=$(gh pr view $PR_NUMBER --json title --jq '.labels.[].name')
          echo "PR_LABELS=$PR_LABELS" >> $GITHUB_OUTPUT

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_PREFIX: "${{ steps.get-pr-info.outputs.PR_TITLE }}"
          PR_BODY: "${{ steps.get-pr-info.outputs.PR_BODY }}"
          PR_LABELS: "${{ steps.get-pr-info.outputs.PR_LABELS }}"
          OVERWRITE_EXISTING_PR: false

      - name: Push sync.yml
        run: |
          git config --global user.name "Gustavo Machado"
          git config --global user.email "gpm22@ic.ac.uk"
          git commit -a -m "Upload sync.yml for debugging purposes"
          git push